### ISSUE TITLE
FOS 9.1.X Compatibility

### ISSUE THREAD

**Issue by atroyblack** [brocade/ansible#101]
Having issues performing one of our playbooks which runs the three below tasks -
```
---
# This playbook will apply zoning for any switch supplied from inventory 
- hosts: all
  gather_facts: False
  collections:
    - brocade.fos

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ https }}"
  vars_files:
    - "inventories/group_vars/{{datacenter}}.yml"

  tasks:

  - name: Create Aliases
    brocade_zoning_alias:
      credential: "{{credential}}"
      vfid: "{{vfid}}"
      aliases: "{{aliases}}"

  - name: Create Zones
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: "{{vfid}}"
      zones: "{{zones}}"

  - name: Create Configs
    brocade_zoning_cfg:
      credential: "{{credential}}"
      vfid: "{{vfid}}"
      cfgs: "{{cfgs}}"
      active_cfg: "{{cfgs[0].name}}"
```

The error we're getting is in relation to a GET request of the effective-configuration -
```
❯ https --auth $stor_user:$stor_pass --verify false GET https://<SWITCH_NAME>/rest/running/zoning/effective-configuration --body
<?xml version="1.0" ?>
<errors xmlns="urn:ietf:params:xml:ns:yang:ietf-restconf">
  <error>
    <error-type>application</error-type>
    <error-tag>unknown-element</error-tag>
    <error-app-tag>Error</error-app-tag>
    <error-message>Invalid REST URI</error-message>
    <error-info>
      <error-code>5</error-code>
      <error-module>rest</error-module>
    </error-info>
  </error>
</errors>
```

It seems like in FOS 9.X the URI changed from -
`<base_uri>/running/zoning/effective-configuration`
to
`<base_uri>/running/brocade-zone/effective-configuration`

This is noted in https://docs.broadcom.com/doc/FOS-90x-REST-API-RM page 583
Looks like https://github.com/brocade/ansible/blob/2fee2195fef52f8351bd3b33a71a598651f7bd87/utils/brocade_zoning.py#L21
still references the prior URI path.
Our environment is current sitting on a mix of FOS 8.2.X and FOS 9.1.X
We've leverage Brocade's FOS Ansible Galaxy. With the current version in our production environment running on collection 1.0.23 which is ~2 years old. We did some testing with the latest Brocade FOS Ansible collection 1.3.0 but ran into the same issue.

I can't say with confidence that this specific URI path issue would be the only issue we're going to see as the playbook isn't able to get passed this first error. But it does look like brocade_zoning.py is referenced in all three tasks of the specific playbook above - https://github.com/brocade/ansible/blob/2fee2195fef52f8351bd3b33a71a598651f7bd87/library/brocade_zoning_alias.py#L166
https://github.com/brocade/ansible/blob/2fee2195fef52f8351bd3b33a71a598651f7bd87/library/brocade_zoning_zone.py#L167
https://github.com/brocade/ansible/blob/2fee2195fef52f8351bd3b33a71a598651f7bd87/library/brocade_zoning_cfg.py#L169

 We did test one of our FOS 8.2.X switches and both `<base_uri>/running/zoning/effective-configuration` and `<base_uri>/running/brocade-zone/effective-configuration` seem to function. I have to assume that in 8.2.X or earlier had adjustments to the REST API URIs made, but not deprecated till FOS 9.X.

My high level ask would be to understand if and when the repo will be updated to use the most up to date URIs which can support FOS 8.2.X and 9.X as well as when that functionality can be imported into a new version of the Brocade FOS Ansible Galaxy Collection - https://galaxy.ansible.com/brocade/fos
