### ISSUE TITLE
Update documentation on members_add_only and members_remove_only

### ISSUE THREAD

**Issue by tkontogi** [brocade/ansible#112]
Dear Devs team,

To the point.
1. members_add_only & members_remove_only are not task variables but task options:

This will not work:
```
  - name: Create Zone
    vars:
      members_add_only: True
    brocade_zoning_cfg:
      credential: "{{ credentials }}"
```
But this will work:
```
  - name: Create Zone
    brocade_zoning_cfg:
     members_add_only: True
     credential: "{{ credentials }}"
```

2. Both options must be set otherwise the addition does not work:

The below will remove whatever exists in the switch but is missing from the list:

```
  - name: Create Zone
    brocade_zoning_cfg:
      members_add_only: True
      credential: "{{ credential }}"
      vfid: -1
      cfgs:
        - name: Unity_SW1
          members:
            - ENC1_CCS_1_Unity_SPA0_SPB0
 ```
 But this will add whatever exists in the list, to whatever already exists in the switch:

```
  - name: Create Zone
    brocade_zoning_cfg:
      members_add_only: True
      members_remove_only: False
      credential: "{{ credential }}"
      vfid: -1
      cfgs:
        - name: Unity_SW1
          members:
            - ENC1_CCS_1_Unity_SPA0_SPB0
 ```
 
 Thank you.
