### ISSUE TITLE
Adding license key

### ISSUE THREAD

**Issue by olemyk** [brocade/ansible#134]
Hi. Are there any examples of adding a license key

Can't quite find the right combination. 

from [brocade-operation-license](https://techdocs.broadcom.com/us/en/fibre-channel-networking/fabric-os/fabric-os-rest-api/9-0-x/v24113756/brocade-operation-license.html)

it says it wants brocade-operation-license with license-parameters but that doesn't work.

running 9.0.1e1

```
  - name: license add
    brocade.fos.brocade_singleton_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: 'brocade-operation-license' #"brocade-operation-license" #brocade-license
      obj_name: 'action' #"license" #name #
      attributes: 
          action: 'install'
          name:  RRmtMRGYg4MZ9EPHaWsfdgBCHBtCEaDCLBAQYH'
```

```
  - name: license add
    brocade.fos.brocade_singleton_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: 'brocade-license' #"brocade-operation-license" #brocade-license
      obj_name: license #license-parameters #'action' #"license" #name #
      attributes: 
          action: 'install'
          name: 'RRmtMRGYg4MZ9EPHaWadfCHBtCEaDCLBAQYH'
```
