### ISSUE TITLE
Calls to brocade_interface_fibrechannel returns inconsistent data structures for 'neighbors'

### ISSUE THREAD

**Issue by samuellay** [brocade/ansible#136]
The **_brocade.fos.brocade_interface_fibrechannel_**  module returns flogis in 3 different forms.  This requires a lot of extra coding to audit the switches since there are 3 special cases to deal with.

When there are multiple flogis, you get a result that is straight-forward to access in the general case:

```
- name: 3/3
  neighbor:
    wwn: ['20:23:00:14:38:c8:94:fc', '10:00:2e:db:64:d0:00:14', '10:00:2e:db:64:d0:00:00']
```

If a port has no flogis, you get something like this:
```
- name: 3/5
  neighbor: null
```
When it has one flogi you'll get:
```
- name: 3/10
  neighbor: {wwn: '50:00:e1:11:6c:8d:30:16'}
```
It would be a lot easier to extract the data if the data structure was consistent:
```
- name: 3/3
  neighbor:
    wwn: ['20:23:00:14:38:c8:94:fc', '10:00:2e:db:64:d0:00:14', '10:00:2e:db:64:d0:00:00']
- name: 3/5
  neighbor: 
    wwn: []
- name: 3/10
  neighbor: 
    wwn: ['50:00:e1:11:6c:8d:30:16',]
```

Please consider adjusting the data structures for the no-flogi and single-flogi cases to match the multi-flogi (NPIV) case.
