### ISSUE TITLE
Uncaught error when trying to change the default VFID

### ISSUE THREAD

**Issue by mgoetze5** [brocade/ansible#146]
I tried to change the default VFID on a Brocade G720 running FOS 9.1.1c like so:
```
- name: Assign ports to nondefault virtual switchs
  brocade.fos.brocade_fibrechannel_logical_switch_fibrechannel_logical_switch:
    credential: "{{credential}}"
    vfid: -1
    logical_switches: "{{ logical_switch_config }}"
```
with
```
logical_switch_config:
  - fabric_id: 10
    default_switch: true
    base_switch_enabled: 0
    ficon_mode_enabled: 0
    logical_isl_enabled: 1
    port_member_list:
      port_member:
        - "0/0"
        - "0/1"
        - "0/2"
        - "0/3"
        - "0/4"
        - "0/5"
        - "0/6"
        - "0/7"
        - "0/8"
        - "0/9"
        - "0/10"
        - "0/11"
        - "0/12"
        - "0/13"
        - "0/14"
        - "0/15"
        - "0/16"
        - "0/17"
        - "0/18"
        - "0/19"
        - "0/20"
        - "0/21"
        - "0/22"
        - "0/23"
        - "0/24"
        - "0/25"
        - "0/26"
        - "0/27"
        - "0/28"
        - "0/29"
        - "0/30"
        - "0/31"
        - "0/32"
        - "0/33"
        - "0/34"
        - "0/35"
        - "0/36"
        - "0/37"
        - "0/38"
        - "0/39"
        - "0/40"
        - "0/41"
        - "0/42"
        - "0/43"
        - "0/44"
        - "0/45"
        - "0/46"
        - "0/47"
        - "0/48"
        - "0/50"
        - "0/52"
        - "0/54"
        - "0/56"
        - "0/58"
        - "0/60"
        - "0/62"
  - fabric_id: 128
    default_switch: false
    base_switch_enabled: 0
    ficon_mode_enabled: 0
    logical_isl_enabled: 0
    port_member_list:
      port_member:
        - "0/49"
        - "0/51"
        - "0/53"
        - "0/55"
        - "0/57"
        - "0/59"
        - "0/61"
        - "0/63"
```
This works on a switch where I have previously executed ``lscfg --change 128 -newfid 10``. However on a switch with factory default settings I get a 405 response with the following REST error:
```
  "POST_resp_data": {
    "errors": {
      "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
      "error": {
        "error-type": "application",
        "error-tag": "operation-not-supported",
        "error-app-tag": "Error",
        "error-message": "Invalid read-only attribute specified in request",
        "error-info": {
          "error-code": "16717063",
          "error-module": "cal"
        }
      }
    }
  }
```
Expected behaviour is then for ansible to mark the task as failed and abort execution of the playbook, however ansible marked the task as OK and continued execution of the playbook.

PS is there any way to change the VFID of the default LS via API?
