### ISSUE TITLE
Unable to modify long distance for port configuration

### ISSUE THREAD

**Issue by diazj1** [brocade/ansible#152]
Hi:

I'm try to modify long distance configuration for port 0 trying to get the same configuration like with command: "_**portcfglongdistance 0 LS 1 -distance 10**_"

I'm using the follow task:
```
- name: Configuring ISL ports in switch 125
      brocade.fos.brocade_interface_fibrechannel:
        credential: "{{ credential }}"
        vfid: 125
        ports:
          - name: "0/0"
            enabled_state: False
            long_distance: "LS"
            vc_link_init: true
            long_distance_string: "ls"
      delegate_to: localhost
```

But the task is never executed by ansible and it marks it as if the configuration was already done.
Looks like something is missing, for example the distance option to 10 Km but I'm unable to find how to do it.

BR
JC
