### ISSUE TITLE
brocade_facts: https broken in release 2.0.0

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#170]
Using brocade_facts module and setting `https: True` doesn't work correctly in release 2.0.0. Connection is still done via http. Setting `https: self` is doing https connection.

```
  - name: gather Brocade facts
    brocade.fos.brocade_facts:
      credential:
        fos_ip_addr: "{{ hostname }}"
        fos_user_name: "{{ username }}"
        fos_password: "{{ password }}"
        https: True
      vfid: -1
      gather_subset:
        - brocade_security_user_config
        - brocade_security_ldap_role_map

```

Result was: 
```
FAILED - RETRYING: [localhost]: gather Brocade facts (5 retries left).Result was: {
    "POST_resp_code": 403,
    "POST_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": {
                "error-app-tag": "Error",
                "error-info": {
                    "error-code": "58",
                    "error-module": "rest"
                },
                "error-message": "HTTP interface is disabled. Please use HTTPS.",
                "error-tag": "operation-failed",
                "error-type": "application"
            }
        }
    },
    "POST_resp_reason": "Forbidden",
    "POST_url": "http://switchname.local/rest/login",
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "credential": {
                "fos_ip_addr": "switchname.local",
                "fos_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "fos_user_name": "username",
                "https": "True",
                "ssh_hostkeymust": null
            },
            "gather_subset": [
                "brocade_security_user_config",
                "brocade_security_ldap_role_map"
            ],
            "throttle": null,
            "timeout": null,
            "vfid": -1
        }
    },
    "msg": "POST failed",
    "retries": 6
}
```

Ansible Environment
```
$ ansible --version
ansible [core 2.16.3]
  config file = /home/username/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.8 (main, Dec  9 2024, 15:25:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```

Redefining the argument_spec in brocade_facts https://github.com/brocade/ansible/blob/d4dcce8af3a7101169b867219b3e37c00dabd73f/library/brocade_facts.py#L244
to `https=dict(required=True, type='bool')` makes it work again. I doubt this parameter was ever tested correctly. What's so hard in using real certificates?
