### ISSUE TITLE
Can't get an unchanged OK with brocade_list_obj

### ISSUE THREAD

**Issue by mgoetze5** [brocade/ansible#175]
I'm trying to configure a role with the following task:

```
    - name: Create sanrmuser role
      brocade.fos.brocade_list_obj:
        credential: "{{credential}}"
        vfid: -1
        module_name: "brocade_security"
        list_name: "role_config"
        all_entries: False
        entries:
          - name: sanrmuser
            role_description: "RO-User for SANRM"
            class_permissions:
              class_permission:
                - "ADSelect=OM"
                - "AG=O"
                - "Blade=O"
                - "ChassisConfiguration=O"
                - "ChassisManagement=O"
                - "ConfigManagement=O"
                - "DCE=O"
                - "Diagnostics=O"
                - "EthernetConfig=O"
                - "Fabric=O"
                - "FabricRouting=O"
                - "FCoE=O"
                - "FICON=O"
                - "FirmwareKeyManagement=O"
                - "FirmwareManagement=O"
                - "FRUManagement=O"
                - "HA=O"
                - "ISCSI=O"
                - "LayerTwo=O"
                - "License=O"
                - "LocalUserEnvironment=OM"
                - "Logging=O"
                - "LogSupportsave=OM"
                - "ManagementAccessConfiguration=O"
                - "ManagementServer=O"
                - "MAPS=O"
                - "NameServer=O"
                - "Nocheck=OM"
                - "NxPortManagement=O"
                - "PhysicalComputerSystem=O"
                - "PKI=O"
                - "Reboot=O"
                - "RoutingAdvanced=O"
                - "RoutingBasic=O"
                - "Security=O"
                - "SessionManagement=O"
                - "SNMP=O"
                - "Statistics=O"
                - "StatisticsDevice=O"
                - "StatisticsPort=O"
                - "SwitchConfiguration=O"
                - "SwitchManagement=O"
                - "SwitchManagementIPConfiguration=O"
                - "SwitchPortConfiguration=O"
                - "SwitchPortManagement=O"
                - "SwitchPortSecurityConfiguration=O"
                - "Topology=O"
                - "WWNCard=O"
                - "Zoning=O"
```

This task returns an error **even though it actually successfully makes changes**. The error is:

```
fatal: [fcs-test]: FAILED! =>
    GET_url: https://10.1.2.3/rest/running/brocade-security/role-config
    PATCH_resp_code: 400
    PATCH_resp_data:
        errors:
            '@xmlns': urn:ietf:params:xml:ns:yang:ietf-restconf
            error:
                error-app-tag: Error
                error-info:
                    error-code: '-6'
                    error-module: security
                error-message: Role name should be 4-16 characters in length.
                error-path: /role-config/
                error-tag: Operation-failed
                error-type: protocol
    PATCH_resp_reason: Bad Request
    PATCH_url: https://10.1.2.3/rest/running/brocade-security/role-config
    POST_url: https://10.1.2.3/rest/logout
    add_entries: []
    add_retcode: 0
    changed: false
    current_entries:
...
```

If I don't include the role_description attribute, the task succeeds, but is always marked as "changed" rather than "ok", even if I run it multiple times in a row. If I include "role_type: user-defined" I get an error about trying to change a read-only attribute.

I'm using brocade.fos 2.0.0, ansible 2.17.4 and FOS 9.2.0c.
