### ISSUE TITLE
Please handle PATCH requests that don't change anything appropriately

### ISSUE THREAD

**Issue by mgoetze5** [brocade/ansible#180]
With reference to Defect FOS-833984, I have been informed by BSN Support that it is "working as designed" for the REST API to send a 400 Bad Request response to a PATCH request that doesn't change anything. However, currently Ansible is failing tasks when it gets such a response, aborting execution of the rest of the playbook. As Ansible is meant to be idempotent, it needs to succeed tasks where nothing is changed. So ideally, if the Ansible module identifies that nothing needs to be changed, it wouldn't send a PATCH request at all but simply succeed the task. Alternatively, if it does send a request, apparently a 400 response needs to be treated as a success.

**Comment by mgoetze5** [comment]
For reference here is the Ansible task I am getting sporadic errors on:

```
    - name: Create sanrmuser role
      brocade.fos.brocade_list_obj:
        credential: "{{credential}}"
        vfid: -1
        module_name: "brocade_security"
        list_name: "role_config"
        all_entries: False
        entries:
          - name: sanrmuser
            class_permissions:
              class_permission:
                - "ADSelect=OM"
                - "AG=O"
                - "Blade=O"
                - "ChassisConfiguration=O"
                - "ChassisManagement=O"
                - "ConfigManagement=O"
                - "DCE=O"
                - "Diagnostics=O"
                - "EthernetConfig=O"
                - "Fabric=O"
                - "FabricRouting=O"
                - "FCoE=O"
                - "FICON=O"
                - "FirmwareKeyManagement=O"
                - "FirmwareManagement=O"
                - "FRUManagement=O"
                - "HA=O"
                - "ISCSI=O"
                - "LayerTwo=O"
                - "License=O"
                - "LocalUserEnvironment=OM"
                - "Logging=O"
                - "LogSupportsave=OM"
                - "ManagementAccessConfiguration=O"
                - "ManagementServer=O"
                - "MAPS=O"
                - "NameServer=O"
                - "Nocheck=OM"
                - "NxPortManagement=O"
                - "PhysicalComputerSystem=O"
                - "PKI=O"
                - "Reboot=O"
                - "RoutingAdvanced=O"
                - "RoutingBasic=O"
                - "Security=O"
                - "SessionManagement=O"
                - "SNMP=O"
                - "Statistics=O"
                - "StatisticsDevice=O"
                - "StatisticsPort=O"
                - "SwitchConfiguration=O"
                - "SwitchManagement=O"
                - "SwitchManagementIPConfiguration=O"
                - "SwitchPortConfiguration=O"
                - "SwitchPortManagement=O"
                - "SwitchPortSecurityConfiguration=O"
                - "Topology=O"
                - "WWNCard=O"
                - "Zoning=O"
```
