### ISSUE TITLE
Gathering Information For Single Port

### ISSUE THREAD

**Issue by calebdonald** [brocade/ansible#181]
I'm looking for a way to gather information on a specific port.

I see that this is possible with an API call - https://techdocs.broadcom.com/us/en/fibre-channel-networking/fabric-os/fabric-os-rest-api/9-2-x/GUID-87E16B95-4F30-427F-B487-08C2B855D41B_1/v26048024/brocade-interface-fibrechannel-Examples/Getting-Details-on-a-Single-Fibre-Channel-Port.html

From what I can tell, the closest thing to get the information I need would be the "brocade_list_obj_facts" module. The problem is that this module appears to return port information for every port on the specified vfid, not just the port I want. This creates a lot of extra data to sift through. Am I approaching this incorrectly, or is there a better way to do this with this collection?

Here is what my task looks like:

 ```
- name: Gather facts about single port
   brocade.fos.brocade_list_obj_facts:
     credential: "{{ credential }}"
     vfid: "100"
     module_name: "brocade_interface"
     list_name: "fibrechannel"
     attributes:
       name: "4/1"
```
