### ISSUE TITLE
Issue with enabling root account

### ISSUE THREAD

**Issue by sri4kanne** [brocade/ansible#67]
Hello, while setting up new switch using playbook came across an issue where i'm getting below error when enabling "root" account on the switch. Can you please take a look and let me know if there is a way to include this as part of the playbook? 

Below is the relevant part of the playbook
```
  - name: Enable root & user, and add new api accounts
    brocade_list_obj:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade-security"
      list_name: "user-config"
      all_entries: False
      entries:
        - name: "apiro"
          password: "{{ password_apiro }}"
          virtual_fabric_role_id_list:
            role_id:
              - "admin=1-128"
          chassis_access_role: "user"
        - name: "apirw"
          password: "{{password_apirw}}"
          virtual_fabric_role_id_list:
            role_id:
              - "admin=1-128"
          chassis_access_role: "admin"
        - name: "user"
          account_enabled: True
        - name: "root"
          account_enabled: True 
    tags: useraccount
```

`fatal: [switch]: FAILED! => {"add_entries": [], "add_retcode": 0, "changed": true, "current_entries": [{"access_end_time": null, "access_start_time": null, "account_description": "root", "account_enabled": false, "account_locked": false, "chassis_access_role": "root", "home_virtual_fabric": "128", "name": "root", "password_change_enforced": false, "virtual_fabric_role_id_list": {"role_id": ["root=1-128"]}}, {"access_end_time": null, "access_start_time": null, "account_description": "Administrator", "account_enabled": true, "account_locked": false, "chassis_access_role": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "home_virtual_fabric": "128", "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "password_change_enforced": false, "virtual_fabric_role_id_list": {"role_id": ["********=1-128"]}}`

Below are the commands used in cli which will enable root account and allow ssh access using mgmt/console ports.
`userconfig --change root -e yes` and `rootaccess --set all` are the 2 commands used on cli to enable root access on switch and allow access. Please let me know if you need any more details and thank you for your help!
