### ISSUE TITLE
Changing passwd-cfg with brocade_list_obj doesn't work

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#77]
I wanted to modify the leaf brocade-security/passwd-cfg (passwdcfg on command line) via brocade_list_obj but it doesn't work. Task is returned with "ok" but the configuration stays unchanged.

Playbook: 
```
  - name: password-cfg configuration
    brocade_list_obj:
      credential:
        fos_ip_addr: "{{ inventory_hostname }}"
        <<: *login
      vfid: -1
      all_entries: true
      module_name: "brocade-security"
      list_name: "password-cfg"
      entries:
        - password_config_changed: true
          minimum_length: 20
          minimum_lower_case_character: 1
          minimum_upper_case_character: 1
          minimum_numeric_character: 1
          minimum_special_character: 1
          past_password_history: 10
          maximum_password_age: 180
          warn_on_expire: 10
          lock_out_threshold: 5
          lock_out_duration: 10
    connection: local
```

Output:
```
TASK [password-cfg configuration] ******************************************
ok: [switchname]
```

Is my syntax wrong or is it a bug?

**Comment by daniel-chung-broadcom** [comment]
out of the configurations that you are looking to change, which are the specific ones that failed to update? Do you mind letting me know which specific steps, such as CLIs, to verify the before and after?

**Comment by mamoep** [comment]
None of the specified options were updated.
On cli check „passwdcfg —showall“

**Comment by prabhu-broadcom** [comment]
Hi,
"password_config_changed" is a read-only attribute and that has caused an error in the backend while patching it out. We have tested the playbook without that read-only attribute in the entries list and it works fine. Please remove "password_config_changed" attribute from your playbook and try it out. 

Thanks,

**Comment by mamoep** [comment]
That did the trick, thank you! In the REST API Reference Manual it was written as read-write, so I thought it was needed.

For reference, the following playbook works:
```
  - name: password-cfg configuration
    brocade_list_obj:
      credential:
        fos_ip_addr: "{{ inventory_hostname }}"
        <<: *login
      vfid: -1
      module_name: "brocade-security"
      list_name: "password-cfg"
      entries:
        - minimum_length: 20
          minimum_lower_case_character: 1
          minimum_upper_case_character: 1
          minimum_numeric_character: 1
          minimum_special_character: 1
          past_password_history: 10
          maximum_password_age: 180
          warn_on_expire: 10
          lock_out_threshold: 5
          lock_out_duration: 10
    connection: local
```
