### ISSUE TITLE
brocade_security_sec_crypto_cfg_template_action - Import fails with bracket in remote_user_password

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#78]
I don't know if this is a limitation of the REST API or some issue with the Base64 encoding, but the remote connection for import is not established when there is a bracket in the remote_user_password value. I can see in the connection logs, that the switch doesn't even try to connect to the remote host. After I changed the password to include a different special character the issue was gone.

```
  - hosts: test
    become: false
    collections:
      - brocade.fos
    gather_facts: false
    name: Cipher template test
    vars:
      login: &login
        fos_user_name: "{{ username }}"
        fos_password: "{{ password }}"
        https: self
    tasks:
    - name: Cipher template import
      brocade_security_sec_crypto_cfg_template_action:
        credential:
          fos_ip_addr: "{{ inventory_hostname }}"
          <<: *login
        vfid: -1
        action_inputs:
          remote_user_name: user
          remote_host_ip: "xx.xx.xx.xx"
          remote_user_password: "abc)d1"
          remote_directory: "/tmp/test.file"
          file_transfer_protocol_type: scp
          template_name: new_template
          action: import
      connection: local
```
