### ISSUE TITLE
Zoning facts contain hyphen/dash instead of underscore

### ISSUE THREAD

**Issue by mamoep** [brocade/ansible#83]
I wanted to gather the zoning facts to feed the active configuration back into the brocade_zoning_cfg module. Unfortunately some part of the facts still contain hyphens instead of underscore so trying to address the effective configuration from the facts fails.

Test was done with ansible tower 3.8.2, Ansible 2.9.19 and brocade collection 1.2.0.

**Playbook**
```yaml
  tasks:
  - name: get zoning facts
    brocade_facts:
      credential: "{{ credential }}"
      vfid: -1
      gather_subset:
        - brocade_zoning
    register: brocade_facts
    connection: local
  - name: show zoning
    debug:
      var: brocade_facts.ansible_facts.brocade_zoning
  - name: Add zone {{ create_zone }} to current active configuration {{ brocade_facts.ansible_facts.brocade_zoning.effective-configuration.cfg_name }}
    brocade_zoning_cfg:
      credential: "{{ credential }}"
      vfid: -1
      members_add_only: True
      cfgs:
        - name: "{{ brocade_facts.ansible_facts.brocade_zoning.effective-configuration.cfg_name }}"
          members:
            - "{{ create_zone }}"
      active_cfg: "{{ brocade_facts.ansible_facts.brocade_zoning.effective-configuration.cfg_name }}"
    connection: local
```
**Error**
`The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'effective'`

**Facts**
```json{
    "zoning_facts": {
        "failed": false,
        "changed": false,
        "ansible_facts": {
            "brocade_zoning": {
                "effective-configuration": {
                    "enabled_zone": {
                        "zone_type": "0",
                        "zone_name": "test_zone",
                        "member_entry": {
                            "entry-name": [
                                "12:12:12:12:12:12:12:1a",
                                "12:12:12:12:12:12:12:2a"
                            ]
                        }
                    },
                    "db_committed": "264",
                    "transaction_token": "0",
                    "checksum": "925c5efa18005123657273e63ebbb84c",
                    "default_zone_access": "noaccess",
                    "cfg_name": "cfg_test",
                    "db_chassis_wide_committed": "1276",
                    "cfg_action": "0",
                    "db_transaction": "0",
                    "db_avail": "1042754",
                    "db_max": "1045274"
                },
                "defined-configuration": {
                    "cfg": {
                        "member-zone": {
                            "zone-name": "test_zone"
                        },
                        "cfg-name": "cfg_test"
                    },
                    "zone": [
                        {
                            "zone-type": "0",
                            "member-entry": {
                                "entry-name": [
                                    "12:12:12:12:12:12:12:1a",
                                    "12:12:12:12:12:12:12:2a"
                                ]
                            },
                            "zone-name": "test_zone"
                        },
                        {
                            "zone-type": "0",
                            "member-entry": {
                                "entry-name": [
                                    "test_alias_2",
                                    "test_alias"
                                ]
                            },
                            "zone-name": "test_zone_2"
                        }
                    ],
                    "alias": [
                        {
                            "alias-name": "test_alias",
                            "member-entry": {
                                "alias-entry-name": "12:12:12:12:12:12:12:3a"
                            }
                        },
                        {
                            "alias-name": "test_alias_2",
                            "member-entry": {
                                "alias-entry-name": "12:12:12:12:12:12:12:2b"
                            }
                        }
                    ]
                }
            },
            "discovered_interpreter_python": "/usr/bin/python",
            "ssh_hostkeymust": true
        }
    },
    "changed": false,
    "_ansible_verbose_always": true,
    "_ansible_no_log": false
}```
