### ISSUE TITLE
Specifying 0.0.0.0 as trap recipient for SNMPv3 doesn't work

### ISSUE THREAD

**Issue by munokar** [brocade/ansible#89]
Hi,

the example for configuring SNMPv3 trap recipients show the possibility to configure 0.0.0.0 as recipient like it to done in the CLI to specify that there is not recipient.

Doing so gives me the following error:

`fatal: [xxx.yyy.zzz.com]: FAILED! => {"PATCH_resp_code": 400, "PATCH_resp_data": {"errors": {"@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf", "error": {"error-app-tag": "Error", "error-info": {"error-code": "-1", "error-module": "application"}, "error-message": "0.0.0.0 is invalid ipaddress, please configure valid ipaddress", "error-path": "/v3-trap/trap-index/3/", "error-tag": "Operation-failed", "error-type": "application"}}}`

Looks like 0.0.0.0 is not a valid IP.

Has anyone experienced the same issue?

Regards

Timo

**Comment by daniel-chung-broadcom** [comment]
I was able to set one of the entries to 0.0.0.0. Here is how may index 2 entry looks like 

    v3_traps:
      - trap_index: 1
        host: "10.10.10.11"
        informs_enabled: false
        port_number: 1011
        trap_severity_level: "warning"
        usm_index: 1
      - trap_index: 2
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 2
#      - trap_index: 2
#        host: "10.10.10.10"
#        informs_enabled: false
#        port_number: 1010
#        trap_severity_level: "critical"
#        usm_index: 2
      - trap_index: 3
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 3
      - trap_index: 4
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 4
      - trap_index: 5
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 5
      - trap_index: 6
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 6

and my facts went from

TASK [print accumulative ansible_facts gathered] ***************************************************
ok: [san_eng_zone_seed_san_a] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3",
        "v3_trap": [
            {
                "host": "10.10.10.11",
                "informs_enabled": false,
                "port_number": "1011",
                "trap_index": "1",
                "trap_severity_level": "warning",
                "usm_index": "1"
            },
            {
                "host": "10.10.10.10",
                "informs_enabled": false,
                "port_number": "1010",
                "trap_index": "2",
                "trap_severity_level": "critical",
                "usm_index": "2"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "3",
                "trap_severity_level": "none",
                "usm_index": "3"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "4",
                "trap_severity_level": "none",
                "usm_index": "4"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "5",
                "trap_severity_level": "none",
                "usm_index": "5"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "6",
                "trap_severity_level": "none",
                "usm_index": "6"
            }
        ]
    }
}

to

TASK [print accumulative ansible_facts gathered] ***************************************************
ok: [san_eng_zone_seed_san_a] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3",
        "v3_trap": [
            {
                "host": "10.10.10.11",
                "informs_enabled": false,
                "port_number": "1011",
                "trap_index": "1",
                "trap_severity_level": "warning",
                "usm_index": "1"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "2",
                "trap_severity_level": "none",
                "usm_index": "2"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "3",
                "trap_severity_level": "none",
                "usm_index": "3"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "4",
                "trap_severity_level": "none",
                "usm_index": "4"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "5",
                "trap_severity_level": "none",
                "usm_index": "5"
            },
            {
                "host": "0.0.0.0",
                "informs_enabled": false,
                "port_number": "162",
                "trap_index": "6",
                "trap_severity_level": "none",
                "usm_index": "6"
            }
        ]
    }

are you able to share the details from your playbook to see what is going on?

**Comment by munokar** [comment]
Hi,

this is the playbook:

```
- hosts: all
  connection: local
  become: False
  collections:
    - brocade.fos
  name: setup for SNMP configuration
  vars:
    fos_username: user
    fos_passwd: pass
    credential:
        fos_ip_addr: "{{ inventory_hostname }}"
        fos_user_name: "{{ fos_username }}"
        fos_password: "{{ fos_passwd }}"
        https: self

    v3_traps:
      - trap_index: 1
        host: "10.0.0.1"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "ciritcal"
        usm_index: 1
      - trap_index: 2
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "info"
        usm_index: 2
      - trap_index: 3
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "info"
        usm_index: 3
      - trap_index: 4
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "info"
        usm_index: 4
      - trap_index: 5
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "info"
        usm_index: 5
      - trap_index: 6
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "info"
        usm_index: 6


  tasks:

  - name: set SNMPv3 trap receiver
    brocade_snmp_v3_trap:
      credential: "{{credential}}"
      vfid: -1
      v3_traps: "{{ v3_traps }}"

```
Running this playbook against a FOS 8.2.2d SAN switch produces the following errors:

```
fatal: [switch.xxx.yyy.com]: FAILED! => {
    "PATCH_resp_code": 400,
    "PATCH_resp_data": {
        "errors": {
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-restconf",
            "error": [
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "-1",
                        "error-module": "application"
                    },
                    "error-message": "Invalid severity level",
                    "error-path": "/v3-trap/trap-index/1/",
                    "error-tag": "Operation-failed",
                    "error-type": "application"
                },
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "-1",
                        "error-module": "application"
                    },
                    "error-message": "0.0.0.0 is invalid ipaddress, please configure valid ipaddress",
                    "error-path": "/v3-trap/trap-index/3/",
                    "error-tag": "Operation-failed",
                    "error-type": "application"
                },
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "-1",
                        "error-module": "application"
                    },
                    "error-message": "0.0.0.0 is invalid ipaddress, please configure valid ipaddress",
                    "error-path": "/v3-trap/trap-index/5/",
                    "error-tag": "Operation-failed",
                    "error-type": "application"
                },
                {
                    "error-app-tag": "Error",
                    "error-info": {
                        "error-code": "-1",
                        "error-module": "application"
                    },
                    "error-message": "0.0.0.0 is invalid ipaddress, please configure valid ipaddress",
                    "error-path": "/v3-trap/trap-index/6/",
                    "error-tag": "Operation-failed",
                    "error-type": "application"
                }
            ]
        }
    },
    "PATCH_resp_reason": "Bad Request",
    "PATCH_url": "https://********/rest/running/brocade-snmp/v3-trap",
```
